version: "3.9"
services:
  db:
    image: postgres
    container_name: todo-app-test-db
    ports:
      - '54321:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-app
  migrate:
    image: migrate/migrate
    container_name: todo-grpc-test-migrate
    depends_on:
      - db
    volumes:
      - ./migration:/migration
    command: ["-path", "/migration", "-database", "postgres://postgres:123456@db:5432/postgres?sslmode=disable", "up"]
    links:
      - db
    networks:
      - todo-app
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    networks:
      - todo-app
    ports:
      - "8082:8082"
    depends_on:
      - migrate
    links:
      - db
    volumes:
      - ./:/app
volumes:
  pgdata:
networks:
  todo-app:
    driver: bridge