app:
  port: 8082
  timezone: Asia/Jakarta
  serviceName: app-todo

database:
  postgres:
    host: localhost
    user: postgres
    password: 123456
    dbName: postgres
    port: 54321
    sslMode: disable
    connectionMaxLifetime: 10
    connectionMaxOpen: 10
    connectionMaxIdle: 5